### ISSUE TITLE
Design mockup

### ISSUE THREAD

**Issue by hyejeejung** [hyejeejung/ntedu_1.0#1]
I'm repurposing the existing NeuroTechX website into the landing page to make sure that the design is streamlined.

**Comment by hyejeejung** [comment]
When I see the image below, it seems easy for me to grab repurpose parts from current NTX website. The effort required for converting this to a high resolution mockup would exceed coding it directly. What do you think?

![wireframe02](https://cloud.githubusercontent.com/assets/6562568/17498929/520451c0-5d98-11e6-85c2-41ee539a1966.jpg)

**Comment by JMazzucco** [comment]
Yeah, I agree. High-res mockups don't seem necessary in this case, since we are not building it from scratch.

**Comment by hyejeejung** [comment]
Awesome. I'll get started and let you know tomorrow how I went. Thanks, John!
